### ISSUE TITLE
Sumar botón para denuncia anónima en el menú superior

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DerechosDeEstudiantes2#15]
"Hacer denuncia anónima"

**Comment by mikesaurio** [comment]
Entre "Hacer una consulta" y "Sobre nosotros" y ponerle "Denuncia anónima" (demanda de estudiantes del interior en taller de DD.EE. junto a UNICEF, UTU y CES).

**Comment by fernandouval** [comment]
Listo
