### ISSUE TITLE
Poder agregar enlaces en redacción de derechos

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DerechosDeEstudiantes2#38]
Mejora a futuro, no urgente. Ya ví que acepta HTML pero lo tiene que poder hacer cualquiera.
Puede ser ponerle un editor WYSIWYG que además permita un poco de estilo de texto (negrita, cursiva subrayado), o simplemente un botón para agregar enlaces en el texto.

**Comment by fernandouval** [comment]
Cerramos
