### ISSUE TITLE
Agregar código de Analytics (¡ésta sí es importante!)

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DerechosDeEstudiantes2#41]
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-34702401-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-34702401-13');
</script>

`

**Comment by mikesaurio** [comment]
Done!!!
