### ISSUE TITLE
Admin: permitir hacer pública la pregunta desde el formulario de respuesta

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DerechosDeEstudiantes2#54]
Hoy el proceso es:
- Editar pregunta
- Marcar como pública
- Elegir responder
- Guardar y publicar
Y además genera un timepo donde la pregunta está pública, sin respuesta

Sería mejor si hay un checkbox para hacer pública al momento de responder y reducimos ese proceso a:
- Elegir responder
- Guardar y publicar

**Comment by fernandouval** [comment]
Se cierra
