### ISSUE TITLE
Agregar bloque de preguntas

### ISSUE THREAD

**Issue by fernandouval** [datauy/DerechosDeEstudiantes2#66]
Igual al bloque de denuncias, entre éste y el buscador inicial en la home.

**Comment by danielcarranza** [comment]
**Consultas**
Si no encontraste la respuesta que buscabas, podés hacer una nueva consulta acá. Va a llegar directamente a Secundaria o UTU y la respuesta -además de llegarte por correo- va a quedar visible en el sitio para quienes tengan la misma duda.
(Consultar aquí)

Imagen: usar la del formulario de consultas.
![image](https://user-images.githubusercontent.com/1755382/70059606-d550ca80-15bf-11ea-816d-62b5861341d1.png)

@mikesaurio Con ésto creo que ya se puede hacer.
