### ISSUE TITLE
Modificar interacción de denuncias

### ISSUE THREAD

**Issue by fernandouval** [datauy/DerechosDeEstudiantes2#67]
Agregar campos teléfono, localidad e institución.
Agregar destinatario "¿A quién va dirigida la pregunta?": Derechos humanos (seleccionada por defecto y se envía siempre), UTU, Secundaria, No sé (envía a derechos humanos)

**Comment by danielcarranza** [comment]
Ajustados todos los textos relacionados a ésto (#69).

**Comment by fernandouval** [comment]
@danielcarranza yo no veo nada de esto ni en prod ni en desarrollo... capaz me estoy fijando mal...

**Comment by fernandouval** [comment]
No dije nada, está en dev. Se prueba y en caso que estése sube y cierra...
