### ISSUE TITLE
El HTML que el admin permite en las respuestas, luego aparece como código en el sitio 😂🤦‍♂️

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DerechosDeEstudiantes2#84]
Video: https://www.dropbox.com/transfer/AAAAABsS7RlQfbds8EKjoOAKLUM4bNU7gswZdkckG_hiJ3G0GaaWGMg

**Comment by fernandouval** [comment]
Esto debiera de está solucionado desde la publicación de la versión 2.0.2
